version: 9.2.9
app_version: 3.5.2
master:
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
  extraVolumes:
    - name: spark-jars
      configMap:
        name: spark-jars
  extraVolumeMounts:
    - mountPath: /opt/bitnami/spark/custom-jars
      name: spark-jars
  extraEnvVars:
    - name: SPARK_HOME
      value: /opt/bitnami/spark
worker:
  replicaCount: 2
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
  extraVolumes:
    - name: spark-jars
      configMap:
        name: spark-jars
  extraVolumeMounts:
    - mountPath: /opt/bitnami/spark/custom-jars
      name: spark-jars
  extraEnvVars:
    - name: SPARK_HOME
      value: /opt/bitnami/spark