# Use a lightweight Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy application files to the container
COPY . .

# Install required Python packages
RUN pip install --no-cache-dir flask 
RUN pip install --no-cache-dir pyhive   
RUN pip install --no-cache-dir thrift
RUN pip install --no-cache-dir thrift-sasl

# Expose the Flask app's port
EXPOSE 5000

# Command to run the Flask app
CMD ["python", "apiBackend.py"]
